/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal.Interfaz;

/**
 *
 * @author USUARIO
 */
public class Menu extends javax.swing.JFrame {



    /**
     * Creates new form Proveedores
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        opCategorias = new javax.swing.JMenuItem();
        opClientes = new javax.swing.JMenuItem();
        opEmpleados = new javax.swing.JMenuItem();
        opProductos = new javax.swing.JMenuItem();
        opProveedores = new javax.swing.JMenuItem();
        opSalir = new javax.swing.JMenuItem();
        opPedidos = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        opEnvioPedidos = new javax.swing.JMenuItem();
        opEstadoPedidos = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        opEstadoEnvio = new javax.swing.JMenuItem();
        opStock = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        opRegistroUsuario = new javax.swing.JMenuItem();
        opCambiarContra = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Maestro");

        opCategorias.setMnemonic('o');
        opCategorias.setText("Categorías");
        opCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opCategoriasActionPerformed(evt);
            }
        });
        fileMenu.add(opCategorias);

        opClientes.setMnemonic('s');
        opClientes.setText("Clientes");
        opClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opClientesActionPerformed(evt);
            }
        });
        fileMenu.add(opClientes);

        opEmpleados.setMnemonic('a');
        opEmpleados.setText("Empleados");
        opEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opEmpleadosActionPerformed(evt);
            }
        });
        fileMenu.add(opEmpleados);

        opProductos.setText("Productos");
        opProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opProductosActionPerformed(evt);
            }
        });
        fileMenu.add(opProductos);

        opProveedores.setText("Proveedores");
        opProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opProveedoresActionPerformed(evt);
            }
        });
        fileMenu.add(opProveedores);

        opSalir.setMnemonic('x');
        opSalir.setText("Salir");
        opSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opSalirActionPerformed(evt);
            }
        });
        fileMenu.add(opSalir);

        menuBar.add(fileMenu);

        opPedidos.setMnemonic('e');
        opPedidos.setText("Operaciones");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Pedidos");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        opPedidos.add(cutMenuItem);

        opEnvioPedidos.setMnemonic('y');
        opEnvioPedidos.setText("Envio de pedidos");
        opPedidos.add(opEnvioPedidos);

        menuBar.add(opPedidos);

        opEstadoPedidos.setMnemonic('h');
        opEstadoPedidos.setText("Reportes");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Estado de pedidos");
        opEstadoPedidos.add(contentMenuItem);

        opEstadoEnvio.setMnemonic('a');
        opEstadoEnvio.setText("Estado de envio");
        opEstadoPedidos.add(opEstadoEnvio);

        opStock.setText("Stock de productos");
        opEstadoPedidos.add(opStock);

        menuBar.add(opEstadoPedidos);

        jMenu1.setText("Utilitarios");

        opRegistroUsuario.setText("Registrar nuevo usuario");
        jMenu1.add(opRegistroUsuario);

        opCambiarContra.setText("Cambiar contraseña");
        jMenu1.add(opCambiarContra);

        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_opSalirActionPerformed

    private void opCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opCategoriasActionPerformed
        // TODO add your handling code here:
        Categorias c = new Categorias();
        getDesktopPane().add(c);
        c.show();
        
    
    }//GEN-LAST:event_opCategoriasActionPerformed

    private void opProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opProveedoresActionPerformed
        // TODO add your handling code here:
        Proveedores p = new Proveedores();
        getDesktopPane().add(p);
        p.show();

    }//GEN-LAST:event_opProveedoresActionPerformed

    private void opClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opClientesActionPerformed
        // TODO add your handling code here:
        Clientes c = new Clientes();
        getDesktopPane().add(c);
        c.show();
    }//GEN-LAST:event_opClientesActionPerformed

    private void opEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opEmpleadosActionPerformed
        // TODO add your handling code here:
        Empleados e = new Empleados();
        getDesktopPane().add(e);
        e.show();
        
    }//GEN-LAST:event_opEmpleadosActionPerformed

    private void opProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opProductosActionPerformed
        // TODO add your handling code here:
        Productos p = new Productos();
        getDesktopPane().add(p);
        p.show();
    }//GEN-LAST:event_opProductosActionPerformed

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
        // TODO add your handling code here:
        MaestroEmpleados me = new MaestroEmpleados();
        getDesktopPane().add(me);
        me.show();
    }//GEN-LAST:event_cutMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    public static javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem opCambiarContra;
    private javax.swing.JMenuItem opCategorias;
    private javax.swing.JMenuItem opClientes;
    private javax.swing.JMenuItem opEmpleados;
    private javax.swing.JMenuItem opEnvioPedidos;
    private javax.swing.JMenuItem opEstadoEnvio;
    private javax.swing.JMenu opEstadoPedidos;
    private javax.swing.JMenu opPedidos;
    private javax.swing.JMenuItem opProductos;
    private javax.swing.JMenuItem opProveedores;
    private javax.swing.JMenuItem opRegistroUsuario;
    private javax.swing.JMenuItem opSalir;
    private javax.swing.JMenuItem opStock;
    // End of variables declaration//GEN-END:variables
    /**
     * @return the desktopPane
     */
    public javax.swing.JDesktopPane getDesktopPane() {
        return desktopPane;
    }

    /**
     * @param desktopPane the desktopPane to set
     */
    public void setDesktopPane(javax.swing.JDesktopPane desktopPane) {
        this.desktopPane = desktopPane;
    }
}
